import React, { useRef, useState } from "react";
import { Box, Heading } from "@chakra-ui/react";
import {
  LazyLoadImage,
  LazyLoadComponent,
} from "react-lazy-load-image-component";

const style = {
  imageGallery: {
    display: "flex",
    "flex-wrap": "wrap",
    "justify-content": "center",
  },
  imageGallery__image: {
    width: "100%",
  },
  imageGallery__item: {
    width: "300px",
    height: "300px",
    overflow: "hidden",
  },
};

const ImageGallery = (): any => {
  const [scaled, setScaled] = useState(false);
  let counter = 0;
  const handleLoad = () => {
    counter++;
    console.log(`${counter} loaded`);
  };

  const handleImageClick = (ref: any) => {
    if (scaled) {
      ref.current.style.transform = "scaleX(1)";
    } else {
      ref.current.style.transform = "scaleX(2)";
    }

    setScaled((prev) => !prev);
  };

  const firstImageRef = useRef(null);
  return (
    <>
      <Heading textAlign={"center"}>Image Gallery</Heading>
      <Box className="imageGallery" style={style.imageGallery}>
        <div className="imageGallery__item" style={style.imageGallery__item}>
          <LazyLoadComponent>
            <img
              width="300px"
              height="300px"
              ref={firstImageRef}
              onClick={() => handleImageClick(firstImageRef)}
              onLoad={handleLoad}
              className="imageGallery__image"
              src={
                "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
              }
            />
          </LazyLoadComponent>
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
        <div className="imageGallery__item">
          <LazyLoadImage
            width="300px"
            height="300px"
            effect="blur"
            afterLoad={handleLoad}
            className="imageGallery__image"
            src={
              "https://images.unsplash.com/photo-1613541444699-39429d990353?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
            }
          />
        </div>
      </Box>
    </>
  );
};

export default ImageGallery;
